### ISSUE TITLE
bug: 证书删除后，https代理依旧可以正常访问，需要重启apinto网关，才能生效

### ISSUE THREAD

**Issue by dongsoft** [eolinker/apinto#104]
### Current Behavior

证书删除后，https代理依旧可以正常访问，需要重启apinto网关，才能生效

### Steps to Reproduce

1.调用API删除证书
2.调用http://192.168.64.3:9400/api/certificate 接口，显示证书为空 []
3.尝试利用https访问，例如https://xxx.com:8099/v1/test 依旧可以访问到结果
4.等待10分钟，第二步依旧成立，可以访问https，证明证书尚未测试移除
5.重启apinot后，再次测试发现https不可访问。

### Environment

- APINTO version (run `apinto version`): v0.12.6
- Operating system (run `uname -a`): x86  centos 7.6

**Comment by Dot-Liu** [comment]
收到，五一回来后将发布新版本修复该问题，感谢您的反馈

**Comment by Dot-Liu** [comment]
该问题已经修复，您可以直接更新到最新版的apinto

**Comment by Dot-Liu** [comment]
我将关闭该issue，感谢您的反馈
