### ISSUE TITLE
bug: IP ssl证书不可用，必须域名才能访问到https接口

### ISSUE THREAD

**Issue by dongsoft** [eolinker/apinto#105]
### Current Behavior

 IP ssl证书不可用，必须域名才能访问到https接口
 
 Common Name 为止为IP，证书成功导入后，不能以https 方式访问接口
 ssl设置参考文档：https://blog.51cto.com/u_10624715/3235172

### Steps to Reproduce

1.正确配置IP ssl证书和域名证书
2.https://xxx.com:8099/xxx_xljt/v2/yiyan?format=json 访问正常
3. https://192.168.64.3:8099/xxx_xljt/v2/yiyan?format=json 访问异常

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
收到，我们尝试复现看看，若存在该问题，统一在五一后发布修复版本，感谢您的反馈

**Comment by Dot-Liu** [comment]
该问题已经修复，您可以直接更新到最新版的apinto

**Comment by Dot-Liu** [comment]
我将关闭该issue，感谢您的反馈
