### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by 18380291617** [eolinker/apinto#110]
### Current Behavior

post创建配置（包括service、router、证书）后，存入值将description存到返回值中version字段中，如图
![image](https://github.com/eolinker/apinto/assets/134688926/1b8ba815-d985-436f-9b0b-7de0e6796f39)

### Expected Behavior

返回的description应该存放传入的description中

### Error Logs

![image](https://github.com/eolinker/apinto/assets/134688926/1b8ba815-d985-436f-9b0b-7de0e6796f39)

### Steps to Reproduce

1、添加任意apinto配置（router、service、证书等），即可发现问题

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
当前版本号是？直接运行./apinto version就可以看到版本号

**Comment by 18380291617** [comment]
当前使用的版本号：
Apinto version: 0.12.10

**Comment by Dot-Liu** [comment]
好的。  感谢您的反馈。

**Comment by Dot-Liu** [comment]
该问题已修复，您更新到v0.12.11即可

**Comment by Dot-Liu** [comment]
我将关闭该issue，感谢你的反馈
