### ISSUE TITLE
bug: when apinto-gateway:>0.12.11,Cannot add plugins

### ISSUE THREAD

**Issue by ezjbc** [eolinker/apinto#121]
### Current Behavior

When using Apinto Dashboard(V1)v1.2.1-beta, the apinto version is greater than V0.12.11, and the following error will be displayed when adding the plugin: {"code":500,"error":"invalid character '<' looking for beginning of value","re","message":"Moved Permanently. "}
![eae915ecb28be2b431a7cc28e3d79cc](https://github.com/eolinker/apinto/assets/51684966/07070e28-7b8f-4ed5-be00-33191171932f)
![d6ab91bc3435e41c2344e3988c8312a](https://github.com/eolinker/apinto/assets/51684966/2cfee99b-876f-4e41-ae80-6cffd143a944)

### Steps to Reproduce

eolinker/apinto-dashboard:1.2.1-beta

eolinker/apinto-gateway:>0.12.11

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
The issue has been identified and a new version will be released this week.

**Comment by Dot-Liu** [comment]
The issue has been fixed. You can upgrade to the latest version and I will close the issue.
