### ISSUE TITLE
bug: access-log http_output json自定义引用项嵌套层数超过3层就异常了

### ISSUE THREAD

**Issue by ezjbc** [eolinker/apinto#122]
### Current Behavior

![image](https://github.com/eolinker/apinto/assets/51684966/09410072-5c10-4cba-9cdf-e33bbd053efe)
![image](https://github.com/eolinker/apinto/assets/51684966/1361347d-faa1-43fe-956a-5e74c3957506)

【官方文档标注】：
输出类型为line的formatter输出line格式的日志信息，信息嵌套层数不超过三层。
输出
类型为json的formatter输出json格式的日志信息，自定义引用项嵌套层数没有限制。
【实际测试 httpout 输出】
输出类型为json的formatter输出json格式的日志信息，自定义引用项嵌套层数超过3层就异常了。

### Steps to Reproduce

fields:
    - @http
http:
    - @service
    - @proxy
service:
    - abc as service_name
proxy:
    - $request_uri
    - $proxy_header

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

eolinker/apinto-gateway:0.8.5

**Comment by Dot-Liu** [comment]
收到您的反馈，我们复核验证下

**Comment by Dot-Liu** [comment]
这里的异常是指没有生效是吗？

**Comment by ezjbc** [comment]
> 这里的异常是指没有生效是吗？

不是没生效，是取值就乱了，3层结构以上，他就返回第一层的了

**Comment by Dot-Liu** [comment]
![image](https://github.com/eolinker/apinto/assets/14105999/88f66fbb-1492-45f6-8b14-c5b5ac10a1c8)
首字母大小写没对上

**Comment by Dot-Liu** [comment]
感谢您的支持，我将关闭该issue
