### ISSUE TITLE
bug: jwt鉴权被覆盖的问题

### ISSUE THREAD

**Issue by kaiqiangweinisongxing** [eolinker/apinto#125]
### Current Behavior

basic auth鉴权和jwt鉴权同时上线时， jwt鉴权会被覆盖。当下线了basic auth鉴权，jwt鉴权才生效。

### Steps to Reproduce

1.创建basic auth鉴权，上线。basic auth鉴权生效。
2.创建jwt鉴权，上线。jwt鉴权不生效。
3.下线basic auth鉴权。jwt鉴权不生效。

### Environment

- APINTO version (run `apinto version`):apinto_v0.13.3
- Operating system (run `uname -a`):centos7

**Comment by Dot-Liu** [comment]
收到您的反馈，我们将尽快修复

**Comment by Dot-Liu** [comment]
该问题已修复，更新到最新版本即可，我将关闭该issue
