### ISSUE TITLE
bug: 配置了服务发现nacos后，在控制台将nacos下线，网关依旧输出大量的nacos连接不上的日志

### ISSUE THREAD

**Issue by skybird** [eolinker/apinto#128]
### Current Behavior

![image](https://github.com/eolinker/apinto/assets/2775412/d88297e6-5e8a-4faf-acaf-7f304e07712c)
![image](https://github.com/eolinker/apinto/assets/2775412/b27c737f-d5ea-4a5e-98eb-3b7acea3c80f)

### Expected Behavior

既然nacos服务下线了，就不应该持续输出nacox相关的日志

### Steps to Reproduce

1. 启动一个nacos服务；
2. 在apinto控制台网页端配置nacos，并配置相应接口之前可用；
3. 将网页控制台将nacos下线；
4. 观察apinto的/var/log/apinto/nacos/nacos目录下的日志是否持续输出；

### Environment

apinto版本：v0.13.3
apserver版本：v3.2.0

**Comment by Dot-Liu** [comment]
收到您的反馈，该问题我们尽快处理，处理完后通知您～

**Comment by Dot-Liu** [comment]
该问题已经修复，本周五进行发版

**Comment by Dot-Liu** [comment]
该问题已经发版，请更新到最新版本，先前忘记通知您了

**Comment by Dot-Liu** [comment]
我将关闭该Issue，感谢您的反馈
