### ISSUE TITLE
bug: APINTO start Success!  但是网关并没有启动成功

### ISSUE THREAD

**Issue by wangyuanchen** [eolinker/apinto#130]
### Current Behavior

1.docker restart apinto
2.重启失败

### Expected Behavior

1.docker restart apinto
2.重启成功

### Error Logs

[2023-09-26 16:10:22] [ERRO] the app apinto is running  
APINTO start Success!  
APINTO start Success!  
APINTO start Success!  
APINTO start Success!  
APINTO start Success!  
APINTO start Success!  

### Steps to Reproduce

1.docker restart apinto

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
收到，感谢您的反馈

**Comment by Dot-Liu** [comment]
该问题已修复发布，我们修改了启动脚本，您可更新到最新版本的Docker

**Comment by Dot-Liu** [comment]
我将关闭该Issue，感谢您的反馈
