### ISSUE TITLE
bug: 0.14.8版本的apinto访问配置好的Prometheus输出器的metrics路径，是一个下载gz文件操作，不是正常的metrics数据展示页面

### ISSUE THREAD

**Issue by dongsheng5476** [eolinker/apinto#131]
### Current Behavior

apinto进行了升级，从0.13.2升级到0.14.8，目的是新版本支持更多的插件。
但是在0.14.8版本使用过程中发现了如下问题：
我配置了一个Prometheus的output（name为request_total_prometheus），配置成功后访问metrics路径http://xx.xx.xx.xxx:9400/apinto/metrics/prometheus/request_total_prometheus 出现下载gz文件，正常来说应该是一个metric数据展示页面，
在之前的0.13.2版本上是正常的。

### Expected Behavior

访问metrics路径http://xx.xx.xx.xxx:9400/apinto/metrics/prometheus/request_total_prometheus 打开正常的metric数据展示页面

### Steps to Reproduce

1、配置Prometheus输出器（name为request_total_prometheus）
2、浏览器访问输出器的metrics路径http://xx.xx.xx.xxx:9400/apinto/metrics/prometheus/request_total_prometheus 

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
您好，经过确认，该问题不是BUG
当您在请求时携带了头部`Accept-Encoding`包含`gzip`时，网关会自动将响应压缩成`gz`文件返回
若需要直接阅读明文，可以在请求时不携带该头部，如下图
![image](https://github.com/eolinker/apinto/assets/14105999/ecdabefc-33ca-4859-aca7-3ee43328eca6)

**Comment by Dot-Liu** [comment]
原因已找到，周五发布修复版本

**Comment by Dot-Liu** [comment]
该问题已修复，您可更新到v0.14.9版本
