### ISSUE TITLE
使用http_to_grpc插件代理grpc服务，使用postman无法获取响应

### ISSUE THREAD

**Issue by jewdore** [eolinker/apinto#140]
### Current Behavior

在router开启http_to_grpc插件后，使用postman请求对应的api会返回
![image](https://github.com/eolinker/apinto/assets/1990860/62da5c76-cef7-4f6d-bef9-decf6605a008)
使用curl -vvv直接请求，response header中发现有
![image](https://github.com/eolinker/apinto/assets/1990860/ff35112d-77b3-4a85-8aeb-eff228130543)

### Steps to Reproduce

1. 直接安装apinto编译包
2. 使用Admin API创建router，router中配置http_to_grpc插件
3. 创建service

### Environment

Apinto version: 0.13.3
Golang version: go version go1.19.4 linux/amd64
Git commit hash: 3ebe4ac81ad3651e9f2399c37687b30afe33364c
Built on: 2023-07-21T10:28:39Z
Built by: goreleaser
Built by eosc version: v0.14.2
- Operating system：
Linux sg-dsp-go-test-01-1155 5.4.17-2136.321.4.el7uek.x86_64 #2 SMP Mon Jun 26 16:20:00 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Dot-Liu** [comment]
该问题已修复，可更新到最新版本
