### ISSUE TITLE
help request: 需要配置鉴权信息才可上线

### ISSUE THREAD

**Issue by jxyk2007** [eolinker/apinto#153]
### Description

需要配置鉴权信息才可上线
在官方demo演示中没有找到这个功能啊
自己通过教程部署的也未找到，是不是免费版本不支持？无法上线接口也无法使用

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

**Comment by zhoushijin** [comment]
![截图 2024-03-19 18-24-34](https://github.com/eolinker/apinto/assets/16933548/89671700-7d83-43c1-bdd7-280f331d8968)
![截图 2024-03-19 18-33-44](https://github.com/eolinker/apinto/assets/16933548/8332dd35-6b71-42be-aa6f-6dfa6f9995c2)
同样的问题

**Comment by Dot-Liu** [comment]
如果您不希望配置鉴权，您上线匿名应用就好了，普通应用必须配置鉴权才可以上线
![image](https://github.com/eolinker/apinto/assets/14105999/684c95d1-fcb9-4657-a65e-e0baf11df639)

**Comment by Dot-Liu** [comment]
如果你没有新的问题，我将关闭该issue，感谢您的支持
