### ISSUE TITLE
bug: If the circuit breaker policy is set to more than 1, the circuit breaker does not automatically fuse

### ISSUE THREAD

**Issue by quanbetter** [eolinker/apinto#167]
### Current Behavior

The circuit breaker policy exceeds 1
It doesn't fuse automatically

### Expected Behavior

Automatic fusing

### Steps to Reproduce

1.The number of failures is set to 2
2.The stress test qps is 20 and all return 500
3.Observation return
![image](https://github.com/user-attachments/assets/b1c2e195-06f9-4cfe-bdd6-3bb88fce2492)

### Environment

APINTO version (run apinto version):0.17.4
Operating system (run uname -a):Darwin SZ-110200200069.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

**Comment by Dot-Liu** [comment]
This issue has been released in the latest version, please update to the latest version.
