### ISSUE TITLE
nacos接入问题

### ISSUE THREAD

**Issue by dhazy** [eolinker/apinto#49]
### Current State

nacos接入  api提示成功了返回信息也正常   但是nacos中并未发现apinto网关服务   也没有日志提示是否接入成功  请完善下日志功能和说明文档吧   文档实在是难读

### Desired State

nacos接入  api提示成功了返回信息也正常   但是nacos中并未发现apinto网关服务   也没有日志提示是否接入成功  请完善下日志功能和说明文档吧   文档实在是难读

**Comment by eolinker** [comment]
这个接入的概念不是apinto去注册到nacos，是指从nacos中获取服务的配置
apinto从nacos中获取服务的节点地址存在本地缓存，客户端访问apinto时，就可以自动将流量转发到服务的节点

**Comment by Dot-Liu** [comment]
我将关闭该issue，您有其他问题可以重开该issue
