### ISSUE TITLE
建议可以直接读取文件配置

### ISSUE THREAD

**Issue by Dot-Liu** [eolinker/apinto#52]
### Description

建议apinto可以加载文件配置，新部署的一套apinto没法快速同步配置

**Comment by XeryYue** [comment]
With `yaml` or `json` file ? Or other? , I think you can show a preview list , That way we can get more details for it .

As I know , Go after `1.16` ver can read local file and build in to binary.

**Comment by Dot-Liu** [comment]
In Version v0.3.0 supports file loading, but after the introduction of raft cluster, this scheme is cancelled due to the consideration of data synchronization, and can only be operated using OpenAPI.

However, this is unfriendly. This is a function feature of the program. I hope it can be re supported in the future. For example, it can be loaded by cli command. It also supports the loading and export of file configuration, so that multiple sets of apinto clusters can be deployed quickly.

Like version v0.3.0, yaml files should be supported

**Comment by XeryYue** [comment]
Good Idea hope it, And More i tried run the project yesterday, But after i installed the go mod, I
found that the project can't run, It show loose export `func` like `Parse` in `root` Dir, What's the reason for it? Can you help me? @Dot-Liu

**Comment by Dot-Liu** [comment]
Of course,You can send a screenshot of the problem.

**Comment by XeryYue** [comment]
My local go ver is `1.17`, When i installed the go mod 

![image](https://user-images.githubusercontent.com/52351095/162172103-189a926b-6faa-4d3a-9333-843b8612eb79.png)

After go mod installed . I found that

![image](https://user-images.githubusercontent.com/52351095/162172020-006666ad-e483-4b83-8f2a-55be36290ad0.png)

And I see `go.pkg` don't export this `func`

![image](https://user-images.githubusercontent.com/52351095/162172619-51725447-b32f-450a-8892-233828c55f72.png)

@Dot-Liu

**Comment by Dot-Liu** [comment]
This method has been deprecated and should now be changed to checker.Parse.
This file is a test file and will not affect the main compilation. 
You can change http_service.Parse to checker Parse

**Comment by XeryYue** [comment]
> This method has been deprecated and should now be changed to checker.Parse. This file is a test file and will not affect the main compilation. You can change http_service.Parse to checker Parse

Thanks for your reply, And i think  we should fix them because the error is really intolerable.

**Comment by Dot-Liu** [comment]
You're right. You can also submit after modification, and we will merge

**Comment by Dot-Liu** [comment]
Thank you for your correction.

**Comment by Dot-Liu** [comment]
Apinto provides the official tool apinto import, which supports importing gateway configuration from files. For details, please refer to the [apinto import documentation](https://github.com/eolinker/apinto-import/blob/main/README.md)

**Comment by Dot-Liu** [comment]
I will close this issue.
