### ISSUE TITLE
docs: https://help.apinto.com/docs/quick/arrange.html  is 404

### ISSUE THREAD

**Issue by strawcarb** [eolinker/apinto#58]
### Current State

The documention for build guide is 404. 
 https://help.apinto.com/docs/quick/arrange.html

### Desired State

Could you please give a build guide?

**Comment by Dot-Liu** [comment]
Sorry, dashboard went online a few days ago. The tutorial website was upgraded synchronously. 
The new address is https://help.apinto.com/docs/apinto/quick/arrange

**Comment by strawcarb** [comment]
Got it.
