### ISSUE TITLE
ssl certificate can be updated dynamically

### ISSUE THREAD

**Issue by xvjialing** [eolinker/apinto#60]
### Description

It is hoped that the function that the ssl certificate can be updated dynamically can be added, because the services that the gateway needs to manage may have different ssl certificates, and the certificates also have the problem of expiration. The certificate information can be submitted to the configuration

**Comment by Dot-Liu** [comment]
OK, we'll let you know when we list the requirements

**Comment by Dot-Liu** [comment]
This function has been launched in version 0.9.1. Please update the apito and apito dashboard to the latest version. For detailed tutorials, please refer to [click](https://help.apinto.com/docs/dashboard/certificate/server.html#%E5%8A%9F%E8%83%BD%E6%8F%8F%E8%BF%B0)
I will close the issue, thank you for your comments
