### ISSUE TITLE
[Feature]: support yaml  config alias.

### ISSUE THREAD

**Issue by nonzzz** [eolinker/apinto#61]
### Description

# Background

`Apinto` is a great project. But i found `apinto` already support read `yml` config file. But as we all know `.yaml` is equal with `.yml`. But from the [eosc/config.go](https://github.com/eolinker/eosc/blob/main/config/config.go). I notice it's only read `.yml` suffix file. I think we can set up an constant array containing `.yaml` and `.yml`.Then read `.yml` first.

**Comment by nonzzz** [comment]
#52 Quote this issue.

**Comment by Dot-Liu** [comment]
Thank you for your support.

Apinto stipulates that the default configuration file is `config.yml`. 

If you want to have other suffixes, you can configure the `config` field of `apinto.yml` file, like this
```
 config: config.yaml

 data_dir: ./tmp

 pid_dir: ./tmp/

 log_dir: ./tmp

 socket_dir: ./tmp

 extends_dir: ./tmp/extenders/

# error_log_name:  error.log


# error_log_level: error

# error_log_expire: 7d

# error_log_period: day
```

**Comment by nonzzz** [comment]
@Dot-Liu Thanks. I will close this issue.
