### ISSUE TITLE
docs: Just a discussion

### ISSUE THREAD

**Issue by nonzzz** [eolinker/apinto#64]
### Current State

Currently, I found when `apinto` upgrade. Should update latest link for `readme`. I think it's no necessary. Infer from [releasing](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases). We can know. Can redirect the link. So we don't need update `readme` and `api-docs` any more.

### Desired State

I think we can change the release process to get rid of the version number. In past `apinto-v0.7.0.linux.x64.tar.gz`. For future `apinto-linux.x64.tar.gz` is enough.

**Comment by nonzzz** [comment]
@Dot-Liu cc.

**Comment by Dot-Liu** [comment]
That's great. It's a very good idea. I will update the installation package later. Thank you for your suggestion.

**Comment by nonzzz** [comment]
Thank for you reply. It will make the release process lighter in the future

**Comment by Dot-Liu** [comment]
After communicating with colleagues, we decided not to do so

The version name of the file can effectively reduce the information difference and let the operator know the currently downloaded version number, applicable system and architecture

We learned about other related projects, such as NSQ and Nacos, and they did the same

Thank you very much for your suggestions. The collision of ideas will make this project better.

**Comment by nonzzz** [comment]
@Dot-Liu .Thanks a lot. I will close this issue. In my option for future. `Apinto` will generator many difference `linux` distributions. Staying in the present is also a good option.
