### ISSUE TITLE
bug: 文件内容转发失效

### ISSUE THREAD

**Issue by sywengong** [eolinker/apinto#69]
### Current Behavior

使用form-data方式上传文件，文件内容不能正常转发

### Steps to Reproduce

使用form-data方式上传文件

### Environment

- APINTO version (run `apinto version`): v0.6.4
- Operating system (run `uname -a`): centos

**Comment by Dot-Liu** [comment]
该问题在最新的v0.7.2版本已经修复，您这边可以进行更新升级

**Comment by Dot-Liu** [comment]
apinto从0.6.x升级到0.7.x，需要使用升级工具：apinto-import，[点击](https://github.com/eolinker/apinto-import)可转到对应仓库

**Comment by Dot-Liu** [comment]
我将关闭该issue，感谢您的反馈
