### ISSUE TITLE
The admin thread crashed after the nacos service was shut down

### ISSUE THREAD

**Issue by yangdingshan** [eolinker/apinto#81]
### Current Behavior

shutdown registered nacos service,  restart the apinto, admin collapse. The console keeps printing：admin controller ping...

### Steps to Reproduce

1. Register the nacos service to apinto
2. shutdown nacos service
3. Restart the apinto
4. admin thread collapse

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):
apinto-0.8.1

**Comment by Dot-Liu** [comment]
Thanks for your issue, we will check and repair as soon as possible.

**Comment by Dot-Liu** [comment]
The bug was fixed in v0.8.2. I will close the issue
