### ISSUE TITLE
help request: 如果路由到静态配置的具体资源？

### ISSUE THREAD

**Issue by lsx08** [eolinker/apinto#82]
### Description

假如有一个api服务是：https://api.xxx.com，可以通过https://api.xxx.com/user/all获取所有用户
通过配置服务地静态配置域名为api.xxx.com，请问应该如何通过路由访问到https://api.xxx.com/user/all。

我现在只能通过服务和路由配置以http地方式访问到api.xxx.com，无法访问到https://api.xxx.com/user/all

### Environment

apinto 0.8.4，配合对应dashboard

**Comment by Dot-Liu** [comment]
你是希望`/`转到`/user/all`
还是`/user/all`转到`/user/all`
如果是前者，你可以使用转发重写插件，点击[文档](https://help.apinto.com/docs/apinto/plugins/proxy_rewrite_v2.html#%E6%8F%92%E4%BB%B6%E4%BF%A1%E6%81%AF)了解使用细节
如果是后者，您只要匹配中路由就可以了

**Comment by lsx08** [comment]
> 你是希望`/`转到`/user/all` 还是`/user/all`转到`/user/all` 如果是前者，你可以使用转发重写插件，点击[文档](https://help.apinto.com/docs/apinto/plugins/proxy_rewrite_v2.html#%E6%8F%92%E4%BB%B6%E4%BF%A1%E6%81%AF)了解使用细节 如果是后者，您只要匹配中路由就可以了

希望是后者，我在location里面写了/user/all，但是无法访问到正确的https://api.xxx.com/user/all，返回的结果是http://api.xxx.com的结果，并且https没生效。

**Comment by lsx08** [comment]
> > 你是希望`/`转到`/user/all` 还是`/user/all`转到`/user/all` 如果是前者，你可以使用转发重写插件，点击[文档](https://help.apinto.com/docs/apinto/plugins/proxy_rewrite_v2.html#%E6%8F%92%E4%BB%B6%E4%BF%A1%E6%81%AF)了解使用细节 如果是后者，您只要匹配中路由就可以了
> 
> 希望是后者，我在location里面写了/user/all，但是无法访问到正确的[https://api.xxx.com/user/all，返回的结果是http://api.xxx.com的结果，并且https没生效。](https://api.xxx.com/user/all%EF%BC%8C%E8%BF%94%E5%9B%9E%E7%9A%84%E7%BB%93%E6%9E%9C%E6%98%AFhttp://api.xxx.com%E7%9A%84%E7%BB%93%E6%9E%9C%EF%BC%8C%E5%B9%B6%E4%B8%94https%E6%B2%A1%E7%94%9F%E6%95%88%E3%80%82)

我把接口部署从https换成http，可以了。https是需要专门的配置吗？我这里使用的都是默认配置

**Comment by Dot-Liu** [comment]
还请您提供一下相关信息，直接访问`https://api.xxx.com/user/all`的结果
您的接口是否存在https协议跳转的问题呢？

**Comment by Dot-Liu** [comment]
您好，感谢您的反馈，我们这边复现了，这周内修复更新，感谢您的支持

**Comment by lsx08** [comment]
> 您好，感谢您的反馈，我们这边复现了，这周内修复更新，感谢您的支持

好，期待您地更新~

**Comment by Dot-Liu** [comment]
您好。 相关问题已经更新修复，您可以下载更新到0.8.5版本

**Comment by Dot-Liu** [comment]
我将关闭这个issue，感谢您的支持
