### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by budou0608** [eolinker/apinto#83]
### Current Behavior

环境
Linux version 3.10.0-1160.62.1.el7.x86_64
ldd (GNU libc) 2.17
报错
```sh
/lib64/libc.so.6: version `GLIBC_2.34' not found
/lib64/libc.so.6: version `GLIBC_2.32' not found
```

### Steps to Reproduce

https://github.com/eolinker/apinto/releases/download/v0.9.0/apinto_v0.9.0_linux_amd64.tar.gz

### Environment

- APINTO version (run `apinto version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
您好。 这应该和您的GLIBC版本过低有关，您可以参考该教程去升级一下该版本
https://www.cnblogs.com/gw811/p/3676856.html

**Comment by woodcoal** [comment]
不知道官方使用的 Linux 是哪个版本，又没尝试部署到 centos7 / 8，包括直接安装和docker。

反正我尝试 centos 7.9 无解。很多版本的 linux 都无法正常安装高版本的 glibc，所谓更新 gcc 重新编译只是大炮打蚊子，自我安慰而已。

因此如果不解决这个问题，我觉得无意中就流失了很多想尝试的客户

**Comment by budou0608** [comment]
v0.8.5版本试，部署成功！

**Comment by woodcoal** [comment]
直接使用 386 版本吧，无此问题，刚试用成功

**Comment by Dot-Liu** [comment]
我也觉得奇怪。  自动打包脚本没有改动过。  v0.8.5一切正常，v0.9.x就报了glibc的问题
为了方便后续的升级，我们尽快确定原因并修复

**Comment by Dot-Liu** [comment]
@budou0608 
接下来我们会推出多协议的版本，我们尽快找出glibc的问题，方便您使用新特性

**Comment by Dot-Liu** [comment]
我将关闭该issue，感谢您的反馈
