### ISSUE TITLE
docs: 如何使用ide启动apinto

### ISSUE THREAD

**Issue by xesprni** [eolinker/apinto#93]
### Current State

goland编译后启动项目无法读取同目录下的配置文件

### Desired State

如何使用ide启动apinto

**Comment by xesprni** [comment]
.

**Comment by xesprni** [comment]
能启动,但是debug好像有点问题

**Comment by Dot-Liu** [comment]
抱歉。  您可以提供更加详细的信息，我们可以进一步了解

**Comment by baker-yuan** [comment]
> 能启动,但是debug好像有点问题

试一试我这个：http://www.baker-yuan.cn/articles/373

**Comment by Dot-Liu** [comment]
我将关闭这个issue，感谢您的提问
